# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - kmpl-url-shortener

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Cloud5mins.ShortenerTools.Functions' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build -r win-x64 --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          #client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE40453150104CB49B2F62665037A119 }}
          #tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_962851781714499584A55A6FF56E1CDE }}
          #subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_225ADCD131FF4B50951015ADF8A4FABF }}
          creds: '{"clientId":"${{ secrets.AZUREAPPSERVICE_CLIENTID_EE40453150104CB49B2F62665037A119 }}","clientSecret":"${{ secrets.AZUREAPPSERVICE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_225ADCD131FF4B50951015ADF8A4FABF }}","tenantId":"${{ secrets.AZUREAPPSERVICE_TENANTID_962851781714499584A55A6FF56E1CDE }}"}'

      #- uses: azure/login@v2
      #  with:
      #    creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'shortenertool-oa3jr-fa'
          # slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
      #- name: Deploy
      #  uses: azure/webapps-deploy@v2
      #  id: fa
      #  with:
      #    app-name: 'shortenertool-oa3jr-fa'
      #    package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
      #    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}          
